Run 1: with line 80 of "bdrc-airflow" set to
# user:1001
the service is running as the dockerd service: fails with permission denied (as expected)
[2024-03-26T16:39:40.397+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_access_permissions_dag.test_access_permissions manual__2024-03-26T16:39:39.039608+00:00 [queued]>
[2024-03-26T16:39:40.397+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-26T16:39:40.428+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): test_access_permissions> on 2024-03-26 16:39:39.039608+00:00
[2024-03-26T16:39:40.438+0000] {standard_task_runner.py:60} INFO - Started process 211 to run task
[2024-03-26T16:39:40.443+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'test_access_permissions_dag', 'test_access_permissions', 'manual__2024-03-26T16:39:39.039608+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/test_dag_access.py', '--cfg-path', '/tmp/tmpmw26ag02']
[2024-03-26T16:39:40.446+0000] {standard_task_runner.py:88} INFO - Job 2: Subtask test_access_permissions
[2024-03-26T16:39:40.482+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.11/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-03-26T16:39:40.761+0000] {task_command.py:423} INFO - Running <TaskInstance: test_access_permissions_dag.test_access_permissions manual__2024-03-26T16:39:39.039608+00:00 [running]> on host 04780c00beff
[2024-03-26T16:39:40.959+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='test_access_permissions_dag' AIRFLOW_CTX_TASK_ID='test_access_permissions' AIRFLOW_CTX_EXECUTION_DATE='2024-03-26T16:39:39.039608+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-26T16:39:39.039608+00:00'
[2024-03-26T16:39:40.962+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/test_dag_access.py", line 43, in _test_access
    with open(Path.joinpath(test_perms_instance), 'a') as test_perms_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/home/airflow/extern/Archive0/00/TestArchivePermissions/add_multiples'
[2024-03-26T16:39:40.976+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=test_access_permissions_dag, task_id=test_access_permissions, execution_date=20240326T163939, start_date=20240326T163940, end_date=20240326T163940
[2024-03-26T16:39:40.995+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 2 for task test_access_permissions ([Errno 13] Permission denied: '/home/airflow/extern/Archive0/00/TestArchivePermissions/add_multiples'; 211)
[2024-03-26T16:39:41.017+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1


Run 2: restarted, with
    scheduler:
          user: ${SYNC_ACCESS_UID} #  = 1001
Succeeds
[2024-03-26T16:39:41.051+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-26T16:42:16.650+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_access_permissions_dag.test_access_permissions manual__2024-03-26T16:42:15.573124+00:00 [queued]>
[2024-03-26T16:42:16.663+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_access_permissions_dag.test_access_permissions manual__2024-03-26T16:42:15.573124+00:00 [queued]>
[2024-03-26T16:42:16.663+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-26T16:42:16.684+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): test_access_permissions> on 2024-03-26 16:42:15.573124+00:00
[2024-03-26T16:42:16.692+0000] {standard_task_runner.py:60} INFO - Started process 196 to run task
[2024-03-26T16:42:16.696+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'test_access_permissions_dag', 'test_access_permissions', 'manual__2024-03-26T16:42:15.573124+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/test_dag_access.py', '--cfg-path', '/tmp/tmp2iqkxugq']
[2024-03-26T16:42:16.699+0000] {standard_task_runner.py:88} INFO - Job 2: Subtask test_access_permissions
[2024-03-26T16:42:16.725+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.11/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-03-26T16:42:16.958+0000] {task_command.py:423} INFO - Running <TaskInstance: test_access_permissions_dag.test_access_permissions manual__2024-03-26T16:42:15.573124+00:00 [running]> on host 250700b7a613
[2024-03-26T16:42:17.115+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='test_access_permissions_dag' AIRFLOW_CTX_TASK_ID='test_access_permissions' AIRFLOW_CTX_EXECUTION_DATE='2024-03-26T16:42:15.573124+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-26T16:42:15.573124+00:00'
[2024-03-26T16:42:17.119+0000] {logging_mixin.py:188} INFO - Howdy from :/home/***/extern/Archive0/00/TestArchivePermissions/add_multiples:  on 2024-03-26T16:42:17.119276+00:00
[2024-03-26T16:42:17.120+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-03-26T16:42:17.133+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=test_access_permissions_dag, task_id=test_access_permissions, execution_date=20240326T164215, start_date=20240326T164216, end_date=20240326T164217
[2024-03-26T16:42:17.189+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-26T16:42:17.219+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
